// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: 'fittrack-auth',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Serialize token refresh across tabs so background tabs don't each rotate
    // the refresh token (which causes "refresh token not found" logouts).
    lock: async (name, acquireTimeout, fn) => {
      const navigatorLocks = (globalThis.navigator as Navigator & { locks?: LockManager })?.locks;
      if (!navigatorLocks) return fn();
      return navigatorLocks.request(`fittrack-auth-lock:${name}`, { mode: 'exclusive' }, () => fn());
    },
  },
});
